apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-2xsa
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-2xsa
    app.kubernetes.io/part-of: cin4s-839-0048-app
  name: devfile-sample-2xsa
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-2xsa
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-2xsa
    spec:
      containers:
      - image: quay.io/stonesoup_perfscale/cin4s-839-0048-tenant/cin4s-839-0048-app/devfile-sample-2xsa@sha256:94b218ed64c47a9b72bf4c232cd2aef7bd03da10e5aabccb2da3f48b3658db12
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
